### ISSUE TITLE
Remove linting and test files + setup from all starters

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-starters#106]
## Description

Remove all linting dependencies and configuration:
- `setup.cfg` completely
- linting config from `pyproject.toml`
- linting dependencies from `requirements.txt`: flake8, black, isort

Remove test setup:
- `src/test` directory completely
- `pytest` dependencies from `requirements.txt`

Update e2e test setup to still lint the starters by calling `flake8`, `isort` and `black` commands directly instead of `kedro lint`. 
   - To make these checks all pass we would need to add test setup for flake8, because the default max line length is 79 and we've always worked with a max lint length of 88. 

## Context
Follow up on: https://github.com/kedro-org/kedro/issues/1849

**Comment by astrojuanlu** [comment]
Following the new utilities workflow https://github.com/kedro-org/kedro/issues/2388 we'll keep these files.
