### ISSUE TITLE
Spaceflights starter needs updating to match tutorial

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-starters#107]
## Description
[This issue in the framework](https://github.com/kedro-org/kedro/issues/1874) will update to the tutorial docs for spaceflights. We should update the starter to match the final output of the tutorial.

Other changes/improvements/updates to the tutorial that affect code should also always be pushed through to the starter so they stay in sync.

There's [separate discussion of creating additional tutorials](https://github.com/kedro-org/kedro/issues/1949) (based on Spaceflights) to cover optional/advanced aspects such as reporting with Plotly, experiment tracking and modular pipelines/namespacing.

**Comment by stichbury** [comment]
Duplicating this over in the Framework issues for visibility...

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro/issues/1996
