### ISSUE TITLE
Fix `pyspark` starters

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-starters#123]
### Description

`pyspark` 3.4.0 was released on the 13th of April and has broken our `pyspark-iris` and potentially the other `pyspark` starter. This was initially discovered because the `kedro-docker` e2e tests that use the `pyspark-iris` starter were failing.

It's failing on all builds so Python version 3.7, 3.8, 3.9, 3.10. 
Python 3.7 should be expected as the support is deprecated in Spark 3.4

The problem seems to be when the dataset is loaded. But it's not clear yet why.

### Error
See the logs here: https://app.circleci.com/pipelines/github/kedro-org/kedro-starters/564/workflows/62a766f3-5e4c-4ad2-8e49-5907ec66a426/jobs/5820

### Approach + findings so far

- I've used a project created with the `pyspark-iris` starter to reproduce the error. 

- Through logging statements I've been able to trace the error to the point where the dataset is loaded, specifically to line: https://github.com/kedro-org/kedro/blob/main/kedro/extras/datasets/spark/spark_dataset.py#L386

- I've used this branch to get to that point: https://github.com/kedro-org/kedro/tree/debug-spark-issue
- Note that I've used the `SparkDataset` inside the Kedro package for ease of debugging. 

- Loading the dataset directly in python code works fine:
```python
import pyspark.sql
    from kedro.io import DataCatalog
    from kedro.extras.datasets.spark import SparkDataSet

    spark_ds = SparkDataSet(
        filepath="/Users/merel_theisen/Projects/Testing/spark-issue/data/01_raw/iris.csv",
        file_format="csv",
        load_args={"header": True, "inferSchema": True},
        save_args={"header": True},
    )
    catalog = DataCatalog({"iris": spark_ds})

    df = catalog.load("iris")
```

### Additional info
This line https://github.com/kedro-org/kedro/blob/main/kedro/extras/datasets/spark/spark_dataset.py#L386
Results in:
![Screenshot 2023-04-20 at 10 50 56](https://user-images.githubusercontent.com/49397448/233410540-7f0d49d8-c5e3-405e-8cd7-37f687eae2a1.png)

The main change that seems to be new for 3.4.0 in the methods we use is:
```
 .. versionchanged:: 3.4.0
        Supports Spark Connect.
```

**Comment by deepyaman** [comment]
`context._package_name` is `None`, if you step through to https://github.com/kedro-org/kedro-starters/blob/0.18.7/pyspark-iris/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/hooks.py#L19, and the latest version of Spark doesn't like that. If you pass `"dog"` or something for `appName`, it would be much happier. 🐶 

Now, that raises the question as to why `context._package_name` is None...
