### ISSUE TITLE
Update broken links across all starters

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro-starters#131]
## Description
We found that some links in `pyspark-iris` are broken when reviewing the `databricks-iris` starter.

It would be good to go through all the links in the starters (across docstrings / READMEs), check whether they are broken and if so,  fix them.

**Comment by merelcht** [comment]
Done in https://github.com/kedro-org/kedro-starters/pull/185 and https://github.com/kedro-org/kedro-starters/pull/148
