### ISSUE TITLE
Add Python 3.11 support to `kedro-starters`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro-starters#160]
## Description

- We've already added 3.11 support to Kedro and `kedro-plugins`. For the starters we'll just need to add 3.11 builds to ensure they run properly on Python 3.11.
- Convert the CCI builds into Github Actions

**Comment by SajidAlamQB** [comment]
Should we look at using GitHub actions here at the same time?

**Comment by merelcht** [comment]
> Should we look at using GitHub actions here at the same time?

Yes! I'm guessing the starters build is a lot easier than the `kedro` and `kedro-plugins`, so it's probably not too hard to do that.
