### ISSUE TITLE
Revert changes to `test_requirements.txt` and `requirements.txt` once Kedro 0.19 releases

### ISSUE THREAD

**Issue by SajidAlamQB** [kedro-org/kedro-starters#161]
## Description

Following starters work, https://github.com/kedro-org/kedro-starters/pull/159, we switched to using the `develop` branch in `test_requirements.txt` so starters could use the new add-ons flow from kedro and unblock development. This also meant we had to update kedro-viz to work with `develop` so we had to point all `requirments.txt` from starters to the kedro-viz `main` repo instead of PyPi. 

Once Kedro 0.19.0 and next release of Kedro-Viz is out we can revert these back to the default settings.

- [x] Revert `kedro` to using the `main` branch in `test_requirements.txt` in framework.
- [x] Revert `kedro-viz` pin in `requirments.txt` to point to the release version (PyPi).

**Comment by merelcht** [comment]
Completed in #194
