### ISSUE TITLE
Change the directory structure used for starter pipeline tests to match the new structure used on `kedro pipeline create`

### ISSUE THREAD

**Issue by lrcouto** [kedro-org/kedro-starters#214]
## Description
With the changes to the directory structure applied in https://github.com/kedro-org/kedro/pull/3731 now merged, @ankatiyar proposed updating the structure of folders created by the Kedro starters to match them.

## Context

The current structure has the pipeline tests created by starters placed in `<project root>/tests/pipelines`, while the tests created from the `kedro pipeline create` command go into  `<project root>/tests/pipelines/<pipeline name>`. What is being proposed is to put the pipeline tests from starters into their own directory as well.

For example:

![image](https://github.com/kedro-org/kedro-starters/assets/57910428/f54809fb-19e7-4658-98cb-82afda98c602)

In the image above, we can see `test_data_science.py` that was created by using the `spaceflights-pandas` starter and is located directly in the `tests` directory. The test file for `my_pipeline`, which was created with `kedro pipeline create`, is on it's own directory.

## Possible Implementation
The initial idea would be putting the pipeline tests generated from starters on their own directory. In the aforementioned example, the structure would change from `<project root>/tests/pipelines/test_data_science.py` to  `<project root>/tests/pipelines/data_science/test_pipeline.py`.

**Comment by astrojuanlu** [comment]
Would it make sense to try to fit this for the upcoming 0.19.4 to avoid inconsistencies @merelcht ?

**Comment by merelcht** [comment]
> Would it make sense to try to fit this for the upcoming 0.19.4 to avoid inconsistencies @merelcht ?

Yes this must be done before the release.
