### ISSUE TITLE
Missing .gitignore when using starters

### ISSUE THREAD

**Issue by efongue-tf** [kedro-org/kedro-starters#56]
# Description
The .gitignore file is missing when I tried to create a project using starters.

# Steps to Reproduce
- kedro new --starter=pyspark
- kedro new --starter=pyspark-iris

# Environment
Kedro version used (pip show kedro or kedro -V): 0.17.5
Python version used (python -V): Python 3.8.12

**Comment by noklam** [comment]
I believe they are now in place. See [pyspark](https://github.com/kedro-org/kedro-starters/blob/main/pyspark/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.gitignore) and [pyspark-iris](https://github.com/kedro-org/kedro-starters/blob/main/pyspark-iris/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.gitignore)
