### ISSUE TITLE
[KED-3022] Update and simplify all starters with the 0.18

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro-starters#67]
To be merged after **0.18.0 has been released**.
 * Registration hooks are deleted in 0.18.0, so we should remove all `hooks.py` files containing registration hooks from our starters.
 * Make sure all starters (including the built-in ones) are up to date with Kedro 0.18

**Comment by lorenabalan** [comment]
Closing this are resolved in the 2 linked PRs. Changes are now on branch `0.18.0`, to be merged once kedro 0.18.0 is released.
