### ISSUE TITLE
Kedro new does not work for starter standalone-datacatalog (formerly known as mini-kedro)

### ISSUE THREAD

**Issue by Zemeio** [kedro-org/kedro-starters#84]
## Description
When I run the command `kedro new -s standalone-datacatalog` I get an error saying that the starter is not found.

Just for clarification, the following command works normally as an alternative: `kedro new -s https://github.com/kedro-org/kedro-starters/ --checkout 0.18.0 --directory standalone-datacatalog`

## Context
I was trying to create a minimal project to test how the plugins work. This has an easy workaround, so it does not affect me.

## Steps to Reproduce
1. Run command `kedro new -s standalone-datacatalog` or `kedro new -s standalone-datacatalog --checkout 0.18.0`

## Expected Result
Kedro should move on to ask the normal questions such as project and repo name.

## Actual Result
An error is displayed that says the starter is not found.

```
kedro.framework.cli.utils.KedroCliError: Kedro project template not found at standalone-datacatalog . Specified tag 0.18.0. The following tags are available: . The aliases for the official Kedro starters are: 
- astro-airflow-iris
- mini-kedro
- pandas-iris
- pyspark
- pyspark-iris
- spaceflights

Run with --verbose to see the full exception
Error: Kedro project template not found at standalone-datacatalog . Specified tag 0.18.0. The following tags are available: . The aliases for the official Kedro starters are: 
- astro-airflow-iris
- mini-kedro
- pandas-iris
- pyspark
- pyspark-iris
- spaceflights
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): `kedro, version 0.18.0`
* Python version used (`python -V`): `Python 3.8.5`
* Operating system and version: Windows 10

**Comment by noklam** [comment]
Can confirm this is an issue.
