### ISSUE TITLE
Example Notebook.ipynb in standalone-datacatalog fails with ValueError

### ISSUE THREAD

**Issue by afuetterer** [kedro-org/kedro-starters#86]
## Description

Example Notebook.ipynb in standalone-datacatalog has wrong configloader arguments.

## Context
I wanted to try the Example Notebook.ipynb in the standalone-datacatalog starter.

## Steps to Reproduce
1. Open `standalone-datacatalog/Example Notebook.ipynb` with Jupyter
2. Execute first cell

## Expected Result
It should print the head of the dataframe.

## Actual Result
It fails.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_33865/3764053128.py in <cell line: 8>()
      6 
      7 # Load the data catalog configuration from catalog.yml
----> 8 conf_catalog = conf_loader.get("catalog.yml")
      9 
     10 # Create the DataCatalog instance from the configuration

~/.local/share/virtualenvs/kedro-9vwvPpXf/lib/python3.10/site-packages/kedro/config/config.py in get(self, *patterns)
     97 
     98     def get(self, *patterns: str) -> Dict[str, Any]:
---> 99         return _get_config_from_patterns(
    100             conf_paths=self.conf_paths, patterns=list(patterns)
    101         )

~/.local/share/virtualenvs/kedro-9vwvPpXf/lib/python3.10/site-packages/kedro/config/common.py in _get_config_from_patterns(conf_paths, patterns, ac_template)
     93     for conf_path in conf_paths:
     94         if not Path(conf_path).is_dir():
---> 95             raise ValueError(
     96                 f"Given configuration path either does not exist "
     97                 f"or is not a valid directory: {conf_path}"

ValueError: Given configuration path either does not exist or is not a valid directory: conf/base/base
```

## Possible fix
I am new to kedro, so I don't really understand the ConfigLoader yet.
If I change `conf_loader = ConfigLoader("conf/base")` to `conf_loader = ConfigLoader("conf")` it works though. Is this just on my machine?

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.18.0
* Python version used (`python -V`): Python 3.10.4
* Operating system and version: Manjaro Linux 21.2.6

**Comment by AntonyMilneQB** [comment]
Hi @afuetterer, thanks for your bug report and sorry for the very slow response - we don't often remember to check this repo 😬  This file got outdated when we changed the `ConfigLoader` API a bit in when we released 0.18. Your fix is absolutely right and I've put it in #93.
