### ISSUE TITLE
pyspark-iris tests failing on Windows builds

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro-starters#95]
Following up from #89 - the windows run tests do not pass due to a problem with pyspark-iris. The set-up is a bit tough to dig through and this issue should have it's own dedicated time.

**Comment by SajidAlamQB** [comment]
Pyspark-iris starter needs JDK setup, we could try the win JDK setup we have on the Kedro repo: https://github.com/kedro-org/kedro/blob/2bd2ee27bea25648e60495229a2ef6efaa59a4e2/.circleci/continue_config.yml#L114-L129
