### ISSUE TITLE
Missing tag for Kedro 0.18.2

### ISSUE THREAD

**Issue by Ryojikn** [kedro-org/kedro-starters#99]
Missing tag for Kedro 0.18.2

**Comment by noklam** [comment]
You found the release quick! We haven't officially announced the release yet, this would be done on Monday probably, stay tuned.

For the time being adding  - - checkout 0.18.1 should work

**Comment by noklam** [comment]
The release is out and you should be able to remove any ad-hoc fix now. :)
https://github.com/kedro-org/kedro/tree/0.18.2
